var workCollectionAll = async (ctx, next) => {

    const workCollectionData = [{
        id: 0,
        wlcOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrcc',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download1.jpg',
        workcollectionName: '掌门一对一学习 App UI作品展示',
        workcollectionContent: '<img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc0.jpg" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc1.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc2.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc3.jpg" alt="">',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '2019-10-01',
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: 'http://192.168.2.128:3000/src/assets/user/GGG/GGG.jpg',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrka',
    }, {
        id: 1,
        wlcOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrbb',              
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download2.jpg',
        workcollectionName: '作品二',
        workcollectionContent: '<img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc0.jpg" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc1.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc2.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc3.jpg" alt="">',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '2019-10-01',
        workcollectionCommentIdnumber:112211222, 
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: 'http://192.168.2.128:3000/src/assets/user/GGG/GGG.jpg',        
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrka'
    }, {
        id: 2,
        wlcOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrww',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download3.jpg',
        workcollectionName: '作品三',
        workcollectionContent: '<img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc0.jpg" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc1.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc2.png" alt=""><img style = "width: 100%;" class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc3.jpg" alt="">',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '2019-10-01',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: 'http://192.168.2.128:3000/src/assets/user/GGG/GGG.jpg',        
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrka',
    }, {
        id: 3,
        wlcOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbrqq',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download4.jpg',
        workcollectionName: '作品四',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 13603920211,
        workcollectionUserHeadimg: 'http://192.168.2.128:3000/src/assets/user/KKK/KKK.jpg',
        workcollectionUserNickname: 'zhangsan',
        workcollectionUserName: '张三',
        workcollectionUserOpenkey:'MNFkbS4IWcKla2nSvRkMCs8rq9mUGpecEVLorKgbraa',
    }, {
        id: 4,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download5.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 5,
        wlcOpenkey:'',             
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download6.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 6,
        wlcOpenkey:'',             
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download7.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 7,
        wlcOpenkey:'',            
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download8.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 8,
        wlcOpenkey:'',              
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download0.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 9,
        wlcOpenkey:'',               
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download9.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 10,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download10.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 11,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download11.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 12,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download12.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 13,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download13.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 14,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download14.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 15,
        wlcOpenkey:'',       
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download15.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }, {
        id: 16,
        wlcOpenkey:'',         
        workcollectionHeadimg: 'http://192.168.2.128:3000/src/assets/img/workcollectionHeadImg/download17.jpg',
        workcollectionName: '作品五',
        workcollectionContent: '',
        workcollectionPraise: '20',
        workcollectionCollection: '10',
        workcollectionUptime: '',
        workcollectionCommentIdnumber:null,
        workcollectionUserPhone: 17630022236,
        workcollectionUserHeadimg: '',
        workcollectionUserNickname: 'fantuan',
        workcollectionUserName: '刘志远',
        workcollectionUserOpenkey:'112211221',
    }];
    ctx.response.body = workCollectionData;
}

var workCollectionItem = async (ctx, next) => {
    ctx.response.body = `<img class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc0.jpg" alt="">
    <img class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc1.png" alt="">
    <img class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc2.png" alt="">
    <img class="essayContentboxImg" src="http://192.168.2.128:3000/src/assets/workcollection/chQyaacccyQ/chQyaacccyQ/wc3.jpg" alt="">`
}


module.exports = {
    'GET /workCollectionAll': workCollectionAll
}